apiVersion: skaffold/v4beta7
kind: Config
metadata:
  name: aura

# Build configuration
build:
  local:
    push: false # Use local registry for kind
    useDockerCLI: true
    useBuildkit: true
  artifacts:
    # Backend image
    - image: aura-backend
      context: .
      docker:
        dockerfile: apps/backend/Dockerfile
        target: development
      sync:
        # Sync Python files for hot reload (uvicorn --reload will pick up changes)
        manual:
          - src: "apps/backend/**/*.py"
            dest: /app/apps/backend
          - src: "libs/core-py/**/*.py"
            dest: /app/libs/core-py
          - src: "clients/cli/**/*.py"
            dest: /app/clients/cli

    # Web dashboard image
    - image: aura-web-dashboard
      context: .
      docker:
        dockerfile: apps/web-dashboard/Dockerfile.dev
      sync:
        # Sync Next.js files for hot reload
        manual:
          - src: "apps/web-dashboard/**/*.{ts,tsx,js,jsx,css,json}"
            dest: /app/apps/web-dashboard
            strip: "apps/web-dashboard/"

# Deploy configuration
deploy:
  kustomize:
    paths:
      - k8s/overlays/dev
    flags:
      global: ["--load-restrictor=LoadRestrictionsNone"]

# Port forwarding for local access
portForward:
  - resourceType: service
    resourceName: backend
    namespace: aura-dev
    port: 8000
    localPort: 8000
  - resourceType: service
    resourceName: web-dashboard
    namespace: aura-dev
    port: 3000
    localPort: 3000

# Development profile
profiles:
  - name: dev
    build:
      local:
        push: false
    deploy:
      kustomize:
        paths:
          - k8s/overlays/dev
        flags:
          global: ["--load-restrictor=LoadRestrictionsNone"]
    portForward:
      - resourceType: service
        resourceName: backend
        namespace: aura-dev
        port: 8000
        localPort: 8000
      - resourceType: service
        resourceName: web-dashboard
        namespace: aura-dev
        port: 3000
        localPort: 3000
