import os
import stat
from pathlib import Path

import typer
from rich.console import Console

app = typer.Typer(help="Manage git hooks")
console = Console()

HOOK_SCRIPT = """#!/bin/sh
# Aura Pre-commit Hook
# Auto-generated by "aura hook install"

echo "🛡️  Aura Guard: Auditing changes..."
uv run aura audit --staged
EXIT_CODE=$?

if [ $EXIT_CODE -ne 0 ]; then
    echo "❌ Aura Audit Failed. Please fix the issues above."
    exit 1
fi

echo "✅ Aura Audit Passed."
exit 0
"""


@app.command()
def install():
    """
    Install the Aura pre-commit hook into .git/hooks.
    """
    git_dir = Path(".git")
    if not git_dir.exists():
        console.print("[bold red]Error:[/bold red] Not a git repository (no .git directory found).")
        raise typer.Exit(code=1)

    hooks_dir = git_dir / "hooks"
    hooks_dir.mkdir(exist_ok=True)

    pre_commit_path = hooks_dir / "pre-commit"

    # Write the hook
    with open(pre_commit_path, "w") as f:
        f.write(HOOK_SCRIPT)

    # Make executable
    st = os.stat(pre_commit_path)
    os.chmod(pre_commit_path, st.st_mode | stat.S_IEXEC)

    console.print(
        f"[bold green]Success:[/bold green] Installed pre-commit hook to {pre_commit_path}"
    )
